# --- Site settings ---
title: "Medusa Backend Deployment on AWS ECS Fargate"
description: "A complete hands-on project showcasing serverless deployment of the Medusa backend on AWS ECS Fargate using Terraform and GitHub Actions CI/CD."

# --- Theme settings ---
theme: jekyll-theme-cayman  # Using Cayman Theme for an attractive and clean design

# --- Personalization ---
author: "Pavithra"
email: "pavithrasozhan@gmail.com"

# --- Social links ---
github_username: "amie2001"
github_url: "https://github.com/amie2001/docker-medusa-/blob/project/README.md"
linkedin_url: "https://www.linkedin.com/in/pavithra-cholan-388129284/"  # Replace with your LinkedIn profile

# --- Navbar (customize navigation links) ---
navbar:
  - text: "Home"
    link: "/"
  - text: "GitHub Repo"
    link: "https://github.com/amie2001/docker-medusa-/blob/project/README.md"
  - text: "Video Walkthrough"
    link: "https://drive.google.com/file/d/1veK8mLx2Qqqb4E328lnvLuNVM8HlaCyK/view?usp=sharing"
  - text: "Docs"
    link: "/docs"  # You can link to documentation if applicable

# --- Style settings ---
favicon: "assets/favicon.ico"  # Add a custom favicon image in the 'assets' folder

# --- SEO settings ---
seo:
  meta_title: "Medusa Backend Deployment on AWS"
  meta_description: "This project automates the deployment of Medusa Backend on AWS ECS Fargate with Terraform and GitHub Actions."

# --- Additional customizations (optional) ---
footer_text: "Created by Pavithra | Powered by GitHub Pages"
