title: "🚀 Medusa Project"
description: "Medusa deployment project with Docker, Jenkins, and AWS."

theme: "minimal-mistakes-jekyll"

# Author details
author:
  name: Pavithra

# Repository info
repository: https://github.com/amie2001/docker-medusa-/blob/project/README.md

markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false

# Build excludes
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor

# Highlight theme for code blocks (you can choose colors)
highlight:
  theme: "monokai"

# Disabling the "Show downloads" section
show_downloads: false
