title: "🚀 Medusa Project - Application Deployment"
description: "Production-ready application deployment using Docker, Jenkins, and AWS EKS with Medusa."

theme: "jekyll-theme-minimal"
plugins:
  - jekyll-seo-tag
  - jekyll-feed

show_downloads: false

# Author details
author:
  name: Pavithra

# Repository info
repository: amie2001/medusa-project

# Optional footer or intro
footer_text: >
  👉 To learn more about this project, visit the [GitHub repository](https://github.com/amie2001/medusa-project).

markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false

# Build excludes
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
