title: "Medusa Backend Deployment on AWS ECS with Fargate"
description: "A full-stack deployment of the Medusa open-source headless commerce backend using Terraform and GitHub Actions."
url: "https://your-github-username.github.io"  # Replace with your GitHub Pages URL
baseurl: "/docker-medusa"  # Adjust based on your repository name or path
github_username: "amie2001"  # Optional

theme: "jekyll-theme-gohar"  # Set Chirpy theme

# Social Media Links (LinkedIn instead of Twitter)
social_links:
  - icon: "fab fa-github"
    label: "GitHub"
    url: "https://github.com/amie2001/docker-medusa-/blob/project/README.md"  # Your project GitHub URL
  - icon: "fab fa-linkedin"
    label: "LinkedIn"
    url: "https://www.linkedin.com/in/pavithra-cholan-388129284/"  # Replace with your LinkedIn profile URL

# Enable search feature
search_enabled: true

# Exclude directories and files from the build
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md

# Customize the navigation menu (Optional)
navigation:
  - title: "Home"
    url: "/"
  - title: "About"
    url: "/about"
  - title: "GitHub Repo"
    url: "https://www.linkedin.com/in/pavithra-cholan-388129284/"  # Link to your GitHub repository
  - title: "Video Walkthrough"
    url: "https://drive.google.com/file/d/1veK8mLx2Qqqb4E328lnvLuNVM8HlaCyK/view?usp=sharing"  # Your video link
